export enum CommonErrorCode {
  ARGUMENT_VALIDATION_ERROR = "ARGUMENT_VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  ALREADY_REGISTERED = "ALREADY_REGISTERED",
  LOGIN_INPUT_INVALIDATION = "LOGIN_INPUT_INVALIDATION",
  AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED",
}
