export enum CommonErrorCode {
  ARGUMENT_VALIDATION_ERROR = "ARGUMENT_VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  ALREADY_REGISTERED = "ALREADY_REGISTERED",
  INVALID_LOGIN_INPUT = "INVALID_LOGIN_INPUT",
  AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED",
  INVALID_ROLE = "INVALID_ROLE",
  SAME_PASSWORD_VALUE = "SAME_PASSWORD_VALUE",
}
